name: Update

on:
  schedule:
    - cron: "0 0 31 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.6

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run script
        run: python DL-SCEWIN.py

      - name: Check for update
        run: |
          try {
              $remote_version = Invoke-RestMethod "https://api.github.com/repos/amitxv/SCEWIN/releases/latest"
              $local_version = Get-ChildItem -Path .\SCEWIN\ -Directory | Select-Object -First 1 -ExpandProperty Name

              Add-Content -Path $env:GITHUB_ENV -Value "local_version=$local_version"

              if ($remote_version.name -eq $local_version) {
                  Write-Host "info: latest version already posted"
                  exit 1
              }
          } catch [System.Net.WebException] {
              # release does not exist
          }

      - name: Zip SCEWIN folder
        run: Compress-Archive -Path SCEWIN -DestinationPath SCEWIN.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: SCEWIN.zip
          name: ${{ env.local_version }}
          tag: ${{ env.local_version }}
          token: ${{ secrets.GH_TOKEN }}
