name: Update

on:
  schedule:
    - cron: "0 0 31 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.6

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run script
        run: python DL-SCEWIN.py

      - name: Determine local SCEWIN version
        run: |
          $local_version = Get-ChildItem -Path .\SCEWIN\ -Directory | Select-Object -First 1 -ExpandProperty Name

          Add-Content -Path $env:GITHUB_ENV -Value "local_version=$local_version"

      - name: Check for update
        run: |
          $remote_version = Invoke-RestMethod "https://api.github.com/repos/amitxv/SCEWIN/releases/latest"

          if ($remote_version.name -eq ${{ env.local_version }}) {
            Write-Host "info: latest version already posted"
            exit 1
          }
        if: github.event_name != 'workflow_dispatch'

      - name: Zip SCEWIN folder
        run: Compress-Archive -Path SCEWIN -DestinationPath SCEWIN.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: SCEWIN.zip
          name: ${{ env.local_version }}
          tag: ${{ env.local_version }}
          token: ${{ secrets.GH_TOKEN }}
