name: Update

on:
  schedule:
    - cron: '0 0 31 * *'  # Runs at 00:00 on the 31st of each month, if it exists
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.6'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run script
        run: python DL-SCEWIN.py

      - name: Check for update
        run: |
          $local_version = Get-ChildItem -Path .\SCEWIN\ -Directory | Select-Object -First 1 -ExpandProperty Name
          echo "Local version: $local_version"
          Add-Content -Path $env:GITHUB_ENV -Value "local_version=$local_version"

          try {
              $remote_version = Invoke-RestMethod "https://api.github.com/repos/Eliminater74/SCEWIN/releases/latest"
              echo "Remote version: $($remote_version.name)"

              if ($remote_version.name -eq $local_version) {
                  Write-Host "Info: Latest version already posted."
                  exit 0
              }
          } catch {
              Write-Host "Info: No existing release found or error in retrieving."
          }

      - name: Zip SCEWIN folder
        run: |
          $zipFileName = "SCEWIN_$($env:local_version).zip"
          Compress-Archive -Path SCEWIN -DestinationPath $zipFileName
          echo "zipFileName=$zipFileName" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.zipFileName }}
          name: ${{ env.local_version }}
          tag: ${{ env.local_version }}
          token: ${{ secrets.GH_TOKEN }}
